# Generated by Django 5.2.6 on 2025-10-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitcompletion',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
